export const articleVolumeData = [
  { date: "Jun 15", articles: 312, prev: 280 },
  { date: "Jun 16", articles: 428, prev: 310 },
  { date: "Jun 17", articles: 356, prev: 295 },
  { date: "Jun 18", articles: 489, prev: 340 },
  { date: "Jun 19", articles: 402, prev: 380 },
  { date: "Jun 20", articles: 378, prev: 350 },
  { date: "Jun 21", articles: 290, prev: 270 },
  { date: "Jun 22", articles: 445, prev: 390 },
  { date: "Jun 23", articles: 510, prev: 420 },
  { date: "Jun 24", articles: 463, prev: 415 },
  { date: "Jun 25", articles: 521, prev: 450 },
  { date: "Jun 26", articles: 398, prev: 370 },
  { date: "Jun 27", articles: 476, prev: 440 },
  { date: "Jun 28", articles: 352, prev: 320 },
  { date: "Jun 29", articles: 334, prev: 298 },
  { date: "Jun 30", articles: 498, prev: 460 },
  { date: "Jul 1", articles: 567, prev: 510 },
  { date: "Jul 2", articles: 489, prev: 445 },
  { date: "Jul 3", articles: 534, prev: 490 },
  { date: "Jul 4", articles: 412, prev: 380 },
  { date: "Jul 5", articles: 378, prev: 340 },
  { date: "Jul 6", articles: 445, prev: 400 },
  { date: "Jul 7", articles: 523, prev: 475 },
  { date: "Jul 8", articles: 487, prev: 440 },
  { date: "Jul 9", articles: 556, prev: 510 },
  { date: "Jul 10", articles: 612, prev: 540 },
  { date: "Jul 11", articles: 498, prev: 460 },
  { date: "Jul 12", articles: 543, prev: 490 },
  { date: "Jul 13", articles: 467, prev: 425 },
  { date: "Jul 14", articles: 589, prev: 520 },
];

export const sentimentTrendData = [
  { date: "Jun 15", positive: 128, neutral: 112, negative: 72 },
  { date: "Jun 18", positive: 185, neutral: 178, negative: 126 },
  { date: "Jun 21", positive: 112, neutral: 108, negative: 70 },
  { date: "Jun 24", positive: 198, neutral: 195, negative: 128 },
  { date: "Jun 27", positive: 182, neutral: 170, negative: 124 },
  { date: "Jun 30", positive: 210, neutral: 188, negative: 100 },
  { date: "Jul 3", positive: 245, neutral: 208, negative: 81 },
  { date: "Jul 6", positive: 188, neutral: 172, negative: 85 },
  { date: "Jul 9", positive: 238, neutral: 210, negative: 108 },
  { date: "Jul 12", positive: 232, neutral: 198, negative: 113 },
  { date: "Jul 14", positive: 258, neutral: 212, negative: 119 },
];

export const categoryDistribution = [
  { name: "Bisnis", value: 3240, color: "#3b82f6" },
  { name: "Umum", value: 2890, color: "#6366f1" },
  { name: "Internasional", value: 2156, color: "#8b5cf6" },
  { name: "Hukum", value: 1423, color: "#a855f7" },
  { name: "Regional", value: 1089, color: "#d946ef" },
  { name: "Olahraga", value: 876, color: "#06b6d4" },
  { name: "Teknologi", value: 432, color: "#0ea5e9" },
  { name: "Hiburan", value: 380, color: "#38bdf8" },
];

export const sourceDistribution = [
  { name: "Kompas", articles: 1820, positive: 45, neutral: 35, negative: 20 },
  { name: "Detik", articles: 2340, positive: 38, neutral: 42, negative: 20 },
  { name: "CNN Indonesia", articles: 1560, positive: 35, neutral: 40, negative: 25 },
  { name: "CNBC Indonesia", articles: 1230, positive: 42, neutral: 38, negative: 20 },
  { name: "Tempo", articles: 980, positive: 30, neutral: 45, negative: 25 },
  { name: "Tribun", articles: 1450, positive: 50, neutral: 35, negative: 15 },
  { name: "Liputan6", articles: 1180, positive: 44, neutral: 38, negative: 18 },
  { name: "Kumparan", articles: 890, positive: 40, neutral: 42, negative: 18 },
  { name: "Viva", articles: 670, positive: 36, neutral: 40, negative: 24 },
  { name: "Okezone", articles: 820, positive: 48, neutral: 36, negative: 16 },
  { name: "Sindonews", articles: 546, positive: 42, neutral: 40, negative: 18 },
];

export const trendingTopics = [
  { topic: "ekonomi", mentions: 1842, change: +12.4, sentiment: "positive" as const, trend: [20, 25, 22, 30, 28, 35, 32] },
  { topic: "pemilu", mentions: 1356, change: +8.7, sentiment: "neutral" as const, trend: [15, 18, 20, 16, 22, 19, 24] },
  { topic: "rupiah", mentions: 987, change: -3.2, sentiment: "negative" as const, trend: [30, 25, 28, 22, 20, 18, 22] },
  { topic: "teknologi", mentions: 743, change: +22.1, sentiment: "positive" as const, trend: [10, 12, 15, 18, 20, 22, 28] },
  { topic: "kebijakan publik", mentions: 621, change: +5.6, sentiment: "neutral" as const, trend: [12, 14, 13, 16, 15, 18, 17] },
  { topic: "energi", mentions: 489, change: -1.8, sentiment: "neutral" as const, trend: [18, 16, 15, 14, 16, 15, 14] },
];

export const articles = [
  {
    id: "1",
    headline: "Bank Indonesia Pertahankan Suku Bunga Acuan di Tengah Tekanan Inflasi Global",
    source: "Kompas",
    category: "Bisnis",
    sentiment: "neutral" as const,
    confidence: 0.92,
    published: "2026-07-14T08:32:00",
    excerpt: "Bank Indonesia (BI) memutuskan untuk mempertahankan suku bunga acuan BI Rate di level 6,25% dalam Rapat Dewan Gubernur (RDG) yang berlangsung pada Juli 2026. Keputusan ini diambil dengan mempertimbangkan stabilitas nilai tukar rupiah dan kondisi inflasi global yang masih bergejolak.",
    url: "#",
    saved: false,
  },
  {
    id: "2",
    headline: "Ekspor Kelapa Sawit Indonesia Melonjak 18% di Kuartal Kedua 2026",
    source: "CNBC Indonesia",
    category: "Bisnis",
    sentiment: "positive" as const,
    confidence: 0.96,
    published: "2026-07-14T07:15:00",
    excerpt: "Kinerja ekspor kelapa sawit Indonesia mencatatkan pertumbuhan signifikan sebesar 18% pada kuartal kedua tahun 2026 dibandingkan periode yang sama tahun lalu. Peningkatan ini didorong oleh permintaan yang kuat dari pasar India, China, dan negara-negara di Timur Tengah.",
    url: "#",
    saved: false,
  },
  {
    id: "3",
    headline: "Demonstrasi Buruh Tuntut Kenaikan UMR di Kawasan Industri Bekasi",
    source: "Detik",
    category: "Hukum",
    sentiment: "negative" as const,
    confidence: 0.88,
    published: "2026-07-14T06:45:00",
    excerpt: "Ribuan buruh dari berbagai serikat pekerja menggelar demonstrasi di kawasan industri Bekasi, Jawa Barat, menuntut kenaikan Upah Minimum Regional (UMR) sebesar 15% untuk tahun 2027. Aksi ini berlangsung tertib namun menyebabkan kemacetan di sejumlah akses jalan menuju kawasan industri.",
    url: "#",
    saved: true,
  },
  {
    id: "4",
    headline: "Startup Fintech Lokal Berhasil Raih Pendanaan Seri B Senilai USD 45 Juta",
    source: "Kumparan",
    category: "Teknologi",
    sentiment: "positive" as const,
    confidence: 0.94,
    published: "2026-07-13T16:20:00",
    excerpt: "Sebuah perusahaan teknologi keuangan (fintech) asal Indonesia berhasil menutup putaran pendanaan Seri B senilai USD 45 juta yang dipimpin oleh investor dari Singapura dan Amerika Serikat. Dana ini akan digunakan untuk ekspansi ke pasar Asia Tenggara dan pengembangan produk baru.",
    url: "#",
    saved: false,
  },
  {
    id: "5",
    headline: "Pemerintah Luncurkan Program Transisi Energi Nasional Senilai Rp 500 Triliun",
    source: "Tempo",
    category: "Umum",
    sentiment: "positive" as const,
    confidence: 0.91,
    published: "2026-07-13T14:10:00",
    excerpt: "Pemerintah Indonesia secara resmi meluncurkan Program Transisi Energi Nasional (PTEN) dengan total investasi mencapai Rp 500 triliun hingga tahun 2035. Program ini bertujuan untuk mengurangi ketergantungan pada energi fosil dan meningkatkan porsi energi terbarukan menjadi 44% dari total bauran energi nasional.",
    url: "#",
    saved: false,
  },
  {
    id: "6",
    headline: "KPK Tetapkan Tersangka Baru Kasus Korupsi Pengadaan Alat Kesehatan",
    source: "CNN Indonesia",
    category: "Hukum",
    sentiment: "negative" as const,
    confidence: 0.97,
    published: "2026-07-13T11:30:00",
    excerpt: "Komisi Pemberantasan Korupsi (KPK) menetapkan dua orang tersangka baru dalam kasus dugaan korupsi pengadaan alat kesehatan di Kementerian Kesehatan. Kerugian negara dalam kasus ini diperkirakan mencapai Rp 1,2 triliun berdasarkan audit BPKP.",
    url: "#",
    saved: false,
  },
  {
    id: "7",
    headline: "Tim Nasional Sepak Bola Indonesia Lolos ke Semifinal Piala Asia 2026",
    source: "Tribun",
    category: "Olahraga",
    sentiment: "positive" as const,
    confidence: 0.99,
    published: "2026-07-12T22:45:00",
    excerpt: "Tim Nasional Sepak Bola Indonesia berhasil melangkah ke babak semifinal Piala Asia 2026 setelah mengalahkan Jepang dengan skor 2-1 dalam pertandingan perempat final yang berlangsung dramatis. Gol kemenangan dicetak oleh Marselino Ferdinan pada menit ke-89.",
    url: "#",
    saved: true,
  },
  {
    id: "8",
    headline: "Rupiah Melemah ke Level Rp 16.450 per Dolar AS Akibat Sentimen Pasar Global",
    source: "CNBC Indonesia",
    category: "Bisnis",
    sentiment: "negative" as const,
    confidence: 0.93,
    published: "2026-07-12T09:15:00",
    excerpt: "Nilai tukar rupiah terhadap dolar Amerika Serikat kembali melemah dan menyentuh level Rp 16.450 per USD pada perdagangan Jumat pagi. Pelemahan ini dipicu oleh penguatan indeks dolar AS seiring dengan meningkatnya ketidakpastian kebijakan moneter The Fed.",
    url: "#",
    saved: false,
  },
  {
    id: "9",
    headline: "Pemkot Jakarta Luncurkan Sistem Transportasi Terintegrasi di Lima Koridor Baru",
    source: "Liputan6",
    category: "Regional",
    sentiment: "positive" as const,
    confidence: 0.89,
    published: "2026-07-11T13:00:00",
    excerpt: "Pemerintah Kota Jakarta resmi meluncurkan sistem transportasi terintegrasi di lima koridor baru yang menghubungkan berbagai kawasan di Jakarta Selatan dan Jakarta Timur. Sistem ini mengintegrasikan layanan MRT, LRT, dan bus Transjakarta dalam satu kartu perjalanan.",
    url: "#",
    saved: false,
  },
  {
    id: "10",
    headline: "Investasi Asing Langsung ke Indonesia Naik 24% dalam Semester Pertama 2026",
    source: "Kompas",
    category: "Bisnis",
    sentiment: "positive" as const,
    confidence: 0.95,
    published: "2026-07-11T10:30:00",
    excerpt: "Badan Koordinasi Penanaman Modal (BKPM) melaporkan realisasi Penanaman Modal Asing (PMA) ke Indonesia meningkat 24% secara tahunan pada semester pertama 2026 mencapai USD 23,4 miliar. Sektor manufaktur, infrastruktur digital, dan energi terbarukan menjadi magnet investasi utama.",
    url: "#",
    saved: false,
  },
];

export const insights = [
  {
    id: "1",
    severity: "critical" as const,
    title: "Sentimen Negatif Meningkat",
    description: "Cakupan negatif meningkat 18% hari ini, terutama terkait pelemahan rupiah dan isu ketenagakerjaan.",
    time: "2 jam lalu",
  },
  {
    id: "2",
    severity: "warning" as const,
    title: "Tren Bisnis di Atas Rata-rata",
    description: "Cakupan bisnis sedang tren di atas rata-rata 30 hari sebesar 34%, didorong oleh laporan pendanaan startup.",
    time: "4 jam lalu",
  },
  {
    id: "3",
    severity: "info" as const,
    title: "Berita Berkembang Terdeteksi",
    description: "3 sumber melaporkan cerita yang sama tentang kebijakan suku bunga Bank Indonesia. Konvergensi narasi terdeteksi.",
    time: "5 jam lalu",
  },
  {
    id: "4",
    severity: "info" as const,
    title: "Volume Artikel Tinggi",
    description: "Detik.com mempublikasikan 247 artikel hari ini — 45% di atas rata-rata harian mereka.",
    time: "6 jam lalu",
  },
];

export const dataQualityMetrics = {
  overallScore: 96.2,
  missingDates: 142,
  duplicates: 38,
  staleArticles: 67,
  crawlIssues: 2,
  lastCrawl: "2026-07-15T14:30:00",
  sources: [
    { name: "Kompas", status: "healthy" as const, lastCrawl: "14 menit lalu", articles: 1820, issues: 0 },
    { name: "Detik", status: "healthy" as const, lastCrawl: "8 menit lalu", articles: 2340, issues: 3 },
    { name: "CNN Indonesia", status: "healthy" as const, lastCrawl: "12 menit lalu", articles: 1560, issues: 1 },
    { name: "CNBC Indonesia", status: "healthy" as const, lastCrawl: "10 menit lalu", articles: 1230, issues: 0 },
    { name: "Tempo", status: "warning" as const, lastCrawl: "2 jam lalu", articles: 980, issues: 12 },
    { name: "Tribun", status: "healthy" as const, lastCrawl: "6 menit lalu", articles: 1450, issues: 2 },
    { name: "Liputan6", status: "healthy" as const, lastCrawl: "15 menit lalu", articles: 1180, issues: 0 },
    { name: "Kumparan", status: "healthy" as const, lastCrawl: "20 menit lalu", articles: 890, issues: 1 },
    { name: "Viva", status: "critical" as const, lastCrawl: "6 jam lalu", articles: 670, issues: 28 },
    { name: "Okezone", status: "healthy" as const, lastCrawl: "18 menit lalu", articles: 820, issues: 0 },
    { name: "Sindonews", status: "healthy" as const, lastCrawl: "22 menit lalu", articles: 546, issues: 0 },
  ],
};
